Repository ROCm/rocm-cmake, pull requests merged in 2024-06, with the labels that each got.

#199 Turn off ROCM_SYMLINK_LIBS by default
  share/rocmcmakebuildtools/cmake/ROCMInstallTargets.cmake
Labels: enhancement

#194 Update Read the Docs configuration to use Python 3.10 and latest rocm-docs-core
  .github/workflows/test.yml
  .readthedocs.yaml
  docs/requirements.in
  docs/requirements.txt
  test/docsphinx/docs/.sphinx/requirements.in
  test/docsphinx/docs/.sphinx/requirements.txt
Labels: documentation, dependencies, ci:docs-only

#197 Update RPATH to binaries for PRIVATE lib changes
  share/rocmcmakebuildtools/cmake/ROCMInstallTargets.cmake
Labels: bug

#200 Add RPATH to tests to point to private libraries.
  share/rocmcmakebuildtools/cmake/ROCMTest.cmake
Labels: enhancement
